src/Entity/Journal.php
<?php

namespace App\Entity;

use App\Repository\JournalRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=JournalRepository::class)
 */
class Journal
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $title;

    /**
     * @ORM\Column(type="date")
     */
    private $date;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=7)
     */
    private $backgroud_color;

    /**
     * @ORM\Column(type="string", length=7)
     */
    private $text_color;

    /**
     * @ORM\OneToMany(targetEntity=User::class, mappedBy="journal")
     */
    private $user;

    public function __construct()
    {
        $this->user = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getBackgroudColor(): ?string
    {
        return $this->backgroud_color;
    }

    public function setBackgroudColor(string $backgroud_color): self
    {
        $this->backgroud_color = $backgroud_color;

        return $this;
    }

    public function getTextColor(): ?string
    {
        return $this->text_color;
    }

    public function setTextColor(string $text_color): self
    {
        $this->text_color = $text_color;

        return $this;
    }

    /**
     * @return Collection|user[]
     */
    public function getUser(): Collection
    {
        return $this->user;
    }

    public function addUser(user $user): self
    {
        if (!$this->user->contains($user)) {
            $this->user[] = $user;
            $user->setJournal($this);
        }

        return $this;
    }

    public function removeUser(user $user): self
    {
        if ($this->user->removeElement($user)) {
            // set the owning side to null (unless already changed)
            if ($user->getJournal() === $this) {
                $user->setJournal(null);
            }
        }

        return $this;
    }
}

src/Form/JournalType.php
<?php

namespace App\Form;

use App\Entity\Journal;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class JournalType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('date')
            ->add('content')
            ->add('backgroud_color')
            ->add('text_color')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Journal::class,
        ]);
    }
}

src/Controller/JournalController.php
<?php

namespace App\Controller;

use App\Entity\Journal;
use App\Form\JournalType;
use App\Repository\CalendarRepository;
use App\Repository\JournalRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


/**
 * @Route("/journal")
 */
class JournalController extends AbstractController
{
    /**
     * @Route("/", name="journal_index", methods={"GET"})
     */
    public function index(JournalRepository $journalRepository): Response
    {
        return $this->render('journal/index.html.twig', [
            'journals' => $journalRepository->findAll(),
        ]);
    }
    /**
     * @Route("/new", name="journal_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $journal = new Journal();
        $form = $this->createForm(JournalType::class, $journal);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($journal);
            $entityManager->flush();

            return $this->redirectToRoute('journal_index');
        }
        return $this->render('journal/new.html.twig', [
            'journal' => $journal,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="journal_show", methods={"GET"})
     */

    public function show(Journal $journal): Response
    {
        return $this->render('journal/show.html.twig', [
            'journal' => $journal,
        ]);
    }
    /**
     * @Route("/{id}/edit", name="journal_edit", methods={"GET","POST"})
     */

    public function edit(Request $request, Journal $journal): Response
    {
        $form = $this->createForm(JournalType::class, $journal);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('journal_index');
        }

        return $this->render('journal/edit.html.twig', [
            'journal' => $journal,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="journal_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Journal $journal): Response
    {
        if ($this->isCsrfTokenValid('delete'.$journal->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($journal);
            $entityManager->flush();
        }

        return $this->redirectToRoute('journal_index');
    }
}

templates/journal/_delete_form.html.twig
<form method="post" action="{{ path('journal_delete', {'id': journal.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ journal.id) }}">
    <button class="btn">Delete</button>
</form>

templates/journal/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/journal/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Journal{% endblock %}

{% block body %}
    <h1>Edit Journal</h1>

    {{ include('journal/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('journal_index') }}">back to list</a>

    {{ include('journal/_delete_form.html.twig') }}
{% endblock %}

templates/journal/index.html.twig
{% block body %}
    <link rel="stylesheet" href={{ asset('css/style3.css') }}>

    <div class="container">
            <div class="card-header">
                <div class="table">
                    <h1> Mon journal</h1>
                    {% for journal in journals %}
                        <td >
                           <p id="title">{{  journal.title }}</p>
                        </td>
                        <br>
                        <td>
                            {{ journal.date ? journal.date|date('Y-m-d') : '' }}
                        </td>
                        <br>
                        <div style="width: 70%">
                            <p id="text">{{ journal.content }}</p>
                        </div>
                    <div>
                        <tr>
                            <td>
                                <a href="{{ path('journal_show', {'id': journal.id}) }}">show</a>
                                <a href="{{ path('journal_edit', {'id': journal.id}) }}">edit</a>
                            </td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="7">no records found</td>
                        </tr>
                    {% endfor %}
                    </div>
                </div>

                <a href="{{ path('journal_new') }}">Create new</a>
            </div>
    </div>

{% endblock %}

templates/journal/new.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<title>New Journal</title>
        <link rel="stylesheet" href={{ asset('css/style4.css') }}>
<div id="new">


        <h1 class="cr">Create new Journal</h1>

        {{ include('journal/_form.html.twig') }}

        <button class="btn"><a  href="{{ path('journal_index') }}">back to list</a></button>

</div>
{% endblock %}

templates/journal/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Journal{% endblock %}

{% block body %}
    <h1>Journal</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ journal.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ journal.title }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ journal.date ? journal.date|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Content</th>
                <td>{{ journal.content }}</td>
            </tr>
            <tr>
                <th>Backgroud_color</th>
                <td>{{ journal.backgroudColor }}</td>
            </tr>
            <tr>
                <th>Text_color</th>
                <td>{{ journal.textColor }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('journal_index') }}">back to list</a>

    <a href="{{ path('journal_edit', {'id': journal.id}) }}">edit</a>

    {{ include('journal/_delete_form.html.twig') }}
{% endblock %}